# Generated by Django 2.2.6 on 2019-11-19 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eikan.models.games
import eikan.models.players
import eikan.models.teams


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_type', models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '県大会'), (3, '地区大会'), (4, '甲子園'), (5, 'センバツ')], default=0, verbose_name='大会')),
                ('competiton_round', models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '1回戦'), (3, '2回戦'), (4, '3回戦'), (5, '4回戦'), (6, '準々決勝'), (7, '準決勝'), (8, '決勝')], default=0, verbose_name='回戦')),
                ('result', models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '勝'), (2, '負'), (3, '分')], default=0, verbose_name='勝敗')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='得点')),
                ('run', models.PositiveSmallIntegerField(default=0, verbose_name='失点')),
                ('lank', models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '弱小'), (2, 'そこそこ'), (3, '中堅'), (4, '強豪'), (5, '名門')], default=0, verbose_name='ランク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '試合情報',
                'verbose_name_plural': '試合情報',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.PositiveSmallIntegerField(default=eikan.models.players.default_admission_year, validators=[django.core.validators.MinValueValidator(1939)], verbose_name='入学年度')),
                ('name', models.CharField(max_length=6, verbose_name='名前')),
                ('position', models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '投'), (2, '捕'), (3, '一'), (4, '二'), (5, '三'), (6, '遊'), (7, '外')], default=0, verbose_name='メインポジション')),
                ('is_pitched', models.BooleanField(default=False, verbose_name='野手登板')),
                ('is_ob', models.BooleanField(default=False, verbose_name='OB')),
                ('is_active', models.BooleanField(default=False, verbose_name='現役')),
                ('is_genius', models.BooleanField(default=False, verbose_name='天才')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('is_pitcher', models.BooleanField(default=False, editable=False, verbose_name='投手')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('total_bases', models.PositiveIntegerField(default=0, editable=False, verbose_name='塁打')),
                ('slg', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='長打率')),
                ('obp', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='出塁率')),
                ('gpa', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='GPA')),
                ('batting_average', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='打率')),
                ('bbhp_percent', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='BBHP%')),
                ('isod', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='IsoD')),
                ('isop', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='IsoP')),
                ('bbhp_k', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='BBHP/K')),
                ('p_s', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='P-S')),
                ('era', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='防御率')),
                ('ura', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='失点率')),
                ('whip', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3, verbose_name='WHIP')),
                ('k_bbhp', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='K/BBHP')),
                ('k_9', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='K/9')),
                ('k_percent', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='K%')),
                ('bbhp_9', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='BBHP/9')),
                ('p_bbhp_percent', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='BBHP%')),
                ('hr_9', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3, verbose_name='HR/9')),
                ('hr_percent', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='HR%')),
                ('lob_percent', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='LOB%')),
                ('p_ip', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='P/IP')),
            ],
            options={
                'verbose_name': '選手情報',
                'verbose_name_plural': '選手情報',
                'ordering': ['admission_year', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=eikan.models.teams.default_year, validators=[django.core.validators.MinValueValidator(1941)], verbose_name='年度')),
                ('period', models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '夏'), (2, '秋')], default=eikan.models.teams.default_period, verbose_name='期間')),
                ('prefecture', models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '北北海道'), (2, '南北海道'), (3, '青森'), (4, '岩手'), (5, '宮城'), (6, '秋田'), (7, '山形'), (8, '福島'), (9, '茨城'), (10, '栃木'), (11, '群馬'), (12, '埼玉'), (13, '千葉'), (14, '神奈川'), (15, '山梨'), (16, '東東京'), (17, '西東京'), (18, '新潟'), (19, '富山'), (20, '石川'), (21, '福井'), (22, '長野'), (23, '岐阜'), (24, '静岡'), (25, '愛知'), (26, '三重'), (27, '滋賀'), (28, '京都'), (29, '大阪'), (30, '兵庫'), (31, '奈良'), (32, '和歌山'), (33, '鳥取'), (34, '島根'), (35, '岡山'), (36, '広島'), (37, '山口'), (38, '徳島'), (39, '香川'), (40, '愛媛'), (41, '高知'), (42, '福岡'), (43, '佐賀'), (44, '長崎'), (45, '熊本'), (46, '大分'), (47, '宮崎'), (48, '鹿児島'), (49, '沖縄')], default=0, verbose_name='都道府県')),
                ('training_policy', models.PositiveSmallIntegerField(choices=[(0, '選択'), (1, 'バランス'), (2, '打撃力'), (3, '機動力'), (4, '守備・投手')], default=0, verbose_name='育成方針')),
                ('draft_nomination', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='指名人数')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('total_win', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='勝')),
                ('total_lose', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='負')),
                ('total_draw', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='分')),
                ('score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='得点')),
                ('run', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='失点')),
                ('score_difference', models.IntegerField(default=0, editable=False, verbose_name='得失点差')),
                ('lank', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='ランク')),
                ('batting_average', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='打率')),
                ('ops', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='OPS')),
                ('hr', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='HR')),
                ('era', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='防御率')),
                ('der', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='DER')),
            ],
            options={
                'verbose_name': 'チーム情報',
                'verbose_name_plural': 'チーム情報',
                'ordering': ['-year', '-period'],
            },
        ),
        migrations.CreateModel(
            name='Pitcher_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_started', models.BooleanField(default=False, verbose_name='先発登板')),
                ('innings_pitched', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='イニング')),
                ('innings_pitched_fraction', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='/3')),
                ('total_batters_faced', models.PositiveSmallIntegerField(default=0, verbose_name='対戦打者')),
                ('number_of_pitch', models.PositiveSmallIntegerField(default=0, verbose_name='投球数')),
                ('hit', models.PositiveSmallIntegerField(default=0, verbose_name='被安打')),
                ('strike_out', models.PositiveSmallIntegerField(default=0, verbose_name='三振')),
                ('bases_on_balls', models.PositiveSmallIntegerField(default=0, verbose_name='四球')),
                ('hit_by_pitch', models.PositiveSmallIntegerField(default=0, verbose_name='死球')),
                ('run', models.PositiveSmallIntegerField(default=0, verbose_name='失点')),
                ('earned_run', models.PositiveSmallIntegerField(default=0, verbose_name='自責点')),
                ('wild_pitch', models.PositiveSmallIntegerField(default=0, verbose_name='暴投')),
                ('home_run', models.PositiveSmallIntegerField(default=0, verbose_name='本塁打')),
                ('sacrifice_bunt', models.PositiveSmallIntegerField(default=0, verbose_name='犠打')),
                ('sacrifice_fly', models.PositiveSmallIntegerField(default=0, verbose_name='犠飛')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eikan.Games')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手')),
            ],
            options={
                'verbose_name_plural': '投手成績',
            },
        ),
        migrations.AddField(
            model_name='games',
            name='team_id',
            field=models.ForeignKey(default=eikan.models.games.default_team_id, on_delete=django.db.models.deletion.CASCADE, to='eikan.Teams', verbose_name='チーム'),
        ),
        migrations.CreateModel(
            name='Fielder_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bat', models.PositiveSmallIntegerField(default=0, verbose_name='打数')),
                ('run', models.PositiveSmallIntegerField(default=0, verbose_name='得点')),
                ('hit', models.PositiveSmallIntegerField(default=0, verbose_name='安打')),
                ('two_base', models.PositiveSmallIntegerField(default=0, verbose_name='二塁打')),
                ('three_base', models.PositiveSmallIntegerField(default=0, verbose_name='三塁打')),
                ('home_run', models.PositiveSmallIntegerField(default=0, verbose_name='本塁打')),
                ('run_batted_in', models.PositiveSmallIntegerField(default=0, verbose_name='打点')),
                ('strike_out', models.PositiveSmallIntegerField(default=0, verbose_name='三振')),
                ('bases_on_balls', models.PositiveSmallIntegerField(default=0, verbose_name='四球')),
                ('hit_by_pitch', models.PositiveSmallIntegerField(default=0, verbose_name='死球')),
                ('sacrifice_bunt', models.PositiveSmallIntegerField(default=0, verbose_name='犠打')),
                ('sacrifice_fly', models.PositiveSmallIntegerField(default=0, verbose_name='犠飛')),
                ('stolen_base', models.PositiveSmallIntegerField(default=0, verbose_name='盗塁')),
                ('grounded_into_double_play', models.PositiveSmallIntegerField(default=0, verbose_name='併殺')),
                ('error', models.PositiveSmallIntegerField(default=0, verbose_name='失策')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eikan.Games')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手')),
            ],
            options={
                'verbose_name': '打者一覧',
                'verbose_name_plural': '打者成績',
            },
        ),
    ]
