# Generated by Django 2.2.6 on 2019-11-28 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eikan.models.games
import eikan.models.players


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielder_results',
            name='bases_on_balls',
        ),
        migrations.RemoveField(
            model_name='fielder_results',
            name='hit_by_pitch',
        ),
        migrations.RemoveField(
            model_name='fielder_results',
            name='sacrifice_fly',
        ),
        migrations.RemoveField(
            model_name='pitcher_results',
            name='bases_on_balls',
        ),
        migrations.RemoveField(
            model_name='pitcher_results',
            name='hit_by_pitch',
        ),
        migrations.RemoveField(
            model_name='pitcher_results',
            name='sacrifice_bunt',
        ),
        migrations.RemoveField(
            model_name='pitcher_results',
            name='sacrifice_fly',
        ),
        migrations.AddField(
            model_name='fielder_results',
            name='bb_hbp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='四死球'),
        ),
        migrations.AddField(
            model_name='pitcher_results',
            name='bb_hbp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='四死球'),
        ),
        migrations.AlterField(
            model_name='games',
            name='team_id',
            field=models.ForeignKey(default=eikan.models.games.default_team_id, on_delete=django.db.models.deletion.CASCADE, to='eikan.Teams', verbose_name='チーム'),
        ),
        migrations.AlterField(
            model_name='players',
            name='admission_year',
            field=models.PositiveSmallIntegerField(default=eikan.models.players.default_year, validators=[django.core.validators.MinValueValidator(1939)], verbose_name='入学年度'),
        ),
    ]
