# Generated by Django 2.2.6 on 2020-04-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial_squashed_0012_auto_20200329_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='competition_round',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '1回戦'), (3, '2回戦'), (4, '3回戦'), (5, '準々決勝'), (6, '準決勝'), (7, '決勝')], default=0, verbose_name='回戦'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='training_policy',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, 'バランス'), (2, '打撃力'), (3, '機動力'), (4, '守備・投手')], default=0, verbose_name='育成方針'),
        ),
    ]
