# Generated by Django 2.2.6 on 2020-10-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtotalresults',
            name='game_record',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, verbose_name='戦績'),
        ),
    ]
