# Generated by Django 2.2.6 on 2019-11-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielder_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__gte': 1939, 'admission_year__lte': 9999}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__gte': 1939, 'admission_year__lte': 9999, 'is_pitcher': True}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
    ]
