# Generated by Django 2.2.6 on 2019-12-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersfielder',
            name='ops',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=4, verbose_name='OPS'),
        ),
    ]
