# Generated by Django 2.2.6 on 2020-08-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchertotalresults',
            name='fip',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='FIP'),
        ),
    ]
