# Generated by Django 2.2.6 on 2019-11-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielder_results',
            name='at_bat',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='打数'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='bases_on_balls',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='四球'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='error',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='失策'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='grounded_into_double_play',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='併殺'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='hit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='安打'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='hit_by_pitch',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='死球'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='home_run',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='本塁打'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='run',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='得点'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='run_batted_in',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='打点'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='sacrifice_bunt',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='犠打'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='sacrifice_fly',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='犠飛'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='stolen_base',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='盗塁'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='strike_out',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='三振'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='three_base',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='三塁打'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='two_base',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='二塁打'),
        ),
        migrations.AlterField(
            model_name='games',
            name='competition_type',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '県大会'), (3, '地区大会'), (4, '甲子園'), (5, 'センバツ')], default=0, verbose_name='大会'),
        ),
        migrations.AlterField(
            model_name='games',
            name='competiton_round',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '1回戦'), (3, '2回戦'), (4, '3回戦'), (5, '4回戦'), (6, '準々決勝'), (7, '準決勝'), (8, '決勝')], default=0, verbose_name='回戦'),
        ),
        migrations.AlterField(
            model_name='games',
            name='lank',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '弱小'), (2, 'そこそこ'), (3, '中堅'), (4, '強豪'), (5, '名門')], default=0, verbose_name='ランク'),
        ),
        migrations.AlterField(
            model_name='games',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '勝'), (2, '負'), (3, '分')], default=0, verbose_name='勝敗'),
        ),
        migrations.AlterField(
            model_name='games',
            name='run',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='失点'),
        ),
        migrations.AlterField(
            model_name='games',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='得点'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='bases_on_balls',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='四球'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='earned_run',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='自責点'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='hit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='被安打'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='hit_by_pitch',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='死球'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='home_run',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='本塁打'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='number_of_pitch',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='投球数'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='run',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='失点'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='sacrifice_bunt',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='犠打'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='sacrifice_fly',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='犠飛'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='strike_out',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='三振'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='total_batters_faced',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='対戦打者'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='wild_pitch',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='暴投'),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '投'), (2, '捕'), (3, '一'), (4, '二'), (5, '三'), (6, '遊'), (7, '外')], default=0, verbose_name='メインポジション'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '夏'), (2, '秋')], default=0, verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='prefecture',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '北北海道'), (2, '南北海道'), (3, '青森'), (4, '岩手'), (5, '宮城'), (6, '秋田'), (7, '山形'), (8, '福島'), (9, '茨城'), (10, '栃木'), (11, '群馬'), (12, '埼玉'), (13, '千葉'), (14, '神奈川'), (15, '山梨'), (16, '東東京'), (17, '西東京'), (18, '新潟'), (19, '富山'), (20, '石川'), (21, '福井'), (22, '長野'), (23, '岐阜'), (24, '静岡'), (25, '愛知'), (26, '三重'), (27, '滋賀'), (28, '京都'), (29, '大阪'), (30, '兵庫'), (31, '奈良'), (32, '和歌山'), (33, '鳥取'), (34, '島根'), (35, '岡山'), (36, '広島'), (37, '山口'), (38, '徳島'), (39, '香川'), (40, '愛媛'), (41, '高知'), (42, '福岡'), (43, '佐賀'), (44, '長崎'), (45, '熊本'), (46, '大分'), (47, '宮崎'), (48, '鹿児島'), (49, '沖縄')], default=0, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='training_policy',
            field=models.PositiveSmallIntegerField(choices=[(0, '選択'), (1, 'バランス'), (2, '打撃力'), (3, '機動力'), (4, '守備・投手')], default=0, verbose_name='育成方針'),
        ),
    ]
