# Generated by Django 2.2.6 on 2019-12-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='rank',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True, verbose_name='ランク'),
        ),
    ]
