# Generated by Django 2.2.6 on 2019-11-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielder_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__range': (1940, 1943)}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__range': (1940, 1943), 'position': 1}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
    ]
