# Generated by Django 2.2.6 on 2019-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備考'),
        ),
    ]
