# Generated by Django 2.2.6 on 2020-01-15 06:41

from django.db import migrations, models
import eikan.models.teams


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_auto_20191213_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['admission_year', 'position'], 'verbose_name': '選手情報', 'verbose_name_plural': '(2)選手情報'},
        ),
        migrations.AddField(
            model_name='teamtotalresults',
            name='is_to_win',
            field=models.BooleanField(default=False, editable=False, verbose_name='優勝'),
        ),
        migrations.AlterField(
            model_name='games',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '勝'), (2, '負'), (3, '分')], default=0, editable=False, verbose_name='勝敗'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='prefecture',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '北北海道'), (2, '南北海道'), (3, '青森'), (4, '岩手'), (5, '宮城'), (6, '秋田'), (7, '山形'), (8, '福島'), (9, '茨城'), (10, '栃木'), (11, '群馬'), (12, '埼玉'), (13, '千葉'), (14, '神奈川'), (15, '山梨'), (16, '東東京'), (17, '西東京'), (18, '新潟'), (19, '富山'), (20, '石川'), (21, '福井'), (22, '長野'), (23, '岐阜'), (24, '静岡'), (25, '愛知'), (26, '三重'), (27, '滋賀'), (28, '京都'), (29, '大阪'), (30, '兵庫'), (31, '奈良'), (32, '和歌山'), (33, '鳥取'), (34, '島根'), (35, '岡山'), (36, '広島'), (37, '山口'), (38, '徳島'), (39, '香川'), (40, '愛媛'), (41, '高知'), (42, '福岡'), (43, '佐賀'), (44, '長崎'), (45, '熊本'), (46, '大分'), (47, '宮崎'), (48, '鹿児島'), (49, '沖縄')], default=eikan.models.teams.default_prefecture, verbose_name='都道府県'),
        ),
    ]
