# Generated by Django 2.2.6 on 2019-12-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_auto_20191128_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitcherresults',
            options={'verbose_name': '投手一覧', 'verbose_name_plural': '投手成績'},
        ),
        migrations.RemoveField(
            model_name='players',
            name='batting_average',
        ),
        migrations.RemoveField(
            model_name='players',
            name='bbhp_9',
        ),
        migrations.RemoveField(
            model_name='players',
            name='bbhp_k',
        ),
        migrations.RemoveField(
            model_name='players',
            name='bbhp_percent',
        ),
        migrations.RemoveField(
            model_name='players',
            name='era',
        ),
        migrations.RemoveField(
            model_name='players',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='players',
            name='hr_9',
        ),
        migrations.RemoveField(
            model_name='players',
            name='hr_percent',
        ),
        migrations.RemoveField(
            model_name='players',
            name='isod',
        ),
        migrations.RemoveField(
            model_name='players',
            name='isop',
        ),
        migrations.RemoveField(
            model_name='players',
            name='k_9',
        ),
        migrations.RemoveField(
            model_name='players',
            name='k_bbhp',
        ),
        migrations.RemoveField(
            model_name='players',
            name='k_percent',
        ),
        migrations.RemoveField(
            model_name='players',
            name='lob_percent',
        ),
        migrations.RemoveField(
            model_name='players',
            name='obp',
        ),
        migrations.RemoveField(
            model_name='players',
            name='p_bbhp_percent',
        ),
        migrations.RemoveField(
            model_name='players',
            name='p_ip',
        ),
        migrations.RemoveField(
            model_name='players',
            name='p_s',
        ),
        migrations.RemoveField(
            model_name='players',
            name='slg',
        ),
        migrations.RemoveField(
            model_name='players',
            name='total_bases',
        ),
        migrations.RemoveField(
            model_name='players',
            name='ura',
        ),
        migrations.RemoveField(
            model_name='players',
            name='whip',
        ),
    ]
