# Generated by Django 2.2.6 on 2019-12-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_playersfielder_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerspitcher',
            name='games',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='登板'),
        ),
    ]
