# Generated by Django 2.2.6 on 2019-11-11 02:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_auto_20191105_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fielder_results',
            options={'verbose_name': '打者一覧', 'verbose_name_plural': '打者成績'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['admission_year', 'position'], 'verbose_name': '選手情報', 'verbose_name_plural': '選手情報'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['-year', '-period'], 'verbose_name': 'チーム情報', 'verbose_name_plural': 'チーム情報'},
        ),
        migrations.AddField(
            model_name='players',
            name='is_active_duty',
            field=models.BooleanField(default=False, verbose_name='現役'),
        ),
        migrations.AddField(
            model_name='players',
            name='is_genius',
            field=models.BooleanField(default=False, verbose_name='天才'),
        ),
        migrations.AddField(
            model_name='players',
            name='is_ob',
            field=models.BooleanField(default=False, verbose_name='OB'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__range': (0, 3000)}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='games',
            name='team_id',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='eikan.Teams', verbose_name='チーム'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__range': (0, 3000), 'position': 1}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='players',
            name='admission_year',
            field=models.PositiveSmallIntegerField(default=1939, validators=[django.core.validators.MinValueValidator(1939)], verbose_name='入学年度'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '夏'), (2, '秋')], verbose_name='期間'),
        ),
    ]
