# Generated by Django 2.2.6 on 2020-05-07 05:00

from django.db import migrations, models
import eikan.model_manager


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_auto_20200408_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='is_cold_game',
            field=models.BooleanField(default=False, verbose_name='コールド'),
        ),
        migrations.AlterField(
            model_name='games',
            name='competition_round',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '1回戦'), (3, '2回戦'), (4, '3回戦'), (5, '準々決勝'), (6, '準決勝'), (7, '決勝')], default=eikan.model_manager.DefaultValueExtractor.create_default_competition_round, verbose_name='回戦'),
        ),
        migrations.AlterField(
            model_name='games',
            name='competition_type',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '県大会'), (3, '地区大会'), (4, '甲子園'), (5, 'センバツ')], default=eikan.model_manager.DefaultValueExtractor.create_default_competition_type, verbose_name='大会'),
        ),
    ]
