# Generated by Django 2.2.6 on 2019-11-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_auto_20191112_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='is_pitched',
            field=models.BooleanField(default=False, verbose_name='野手登板'),
        ),
        migrations.AddField(
            model_name='players',
            name='is_pitcher',
            field=models.BooleanField(default=False, editable=False, verbose_name='投手'),
        ),
        migrations.AlterField(
            model_name='fielder_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__gte': 1939, 'admission_year__lte': 1941}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__gte': 1939, 'admission_year__lte': 1941, 'position': 1}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
    ]
