# Generated by Django 2.2.6 on 2020-06-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_modelsettings_is_disable_auto_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtotalresults',
            name='cold_game',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='コールド'),
        ),
        migrations.AddField(
            model_name='teamtotalresults',
            name='mamono_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='魔物使用回数'),
        ),
    ]
