# Generated by Django 2.2.6 on 2020-10-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0002_teamtotalresults_game_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtotalresults',
            name='cold_game',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='コールド'),
        ),
        migrations.AlterField(
            model_name='teamtotalresults',
            name='mamono_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='魔物使用回数'),
        ),
    ]
