# Generated by Django 2.2.6 on 2020-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0003_auto_20200507_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='mamono_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='魔物使用回数'),
        ),
    ]
