# Generated by Django 2.2.6 on 2019-11-11 02:44

import django.core.validators
from django.db import migrations, models
import eikan.models.players


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0003_auto_20191111_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='admission_year',
            field=models.PositiveSmallIntegerField(default=eikan.models.players.default_admission_year, validators=[django.core.validators.MinValueValidator(1939)], verbose_name='入学年度'),
        ),
    ]
