# Generated by Django 2.2.6 on 2019-11-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0003_auto_20191118_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielder_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__gte': 2017, 'admission_year__lte': 2019}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='pitcher_results',
            name='player_id',
            field=models.ForeignKey(limit_choices_to={'admission_year__gte': 2017, 'admission_year__lte': 2019, 'is_pitcher': True}, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
    ]
