# Generated by Django 2.2.6 on 2020-05-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0004_games_mamono_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldertotalresults',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='pitchertotalresults',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='teamtotalresults',
            name='team_id',
        ),
        migrations.AddField(
            model_name='fieldertotalresults',
            name='player',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AddField(
            model_name='pitchertotalresults',
            name='player',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AddField(
            model_name='teamtotalresults',
            name='team',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='eikan.Teams', verbose_name='チーム'),
        ),
    ]
