# Generated by Django 2.2.6 on 2020-01-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0004_auto_20200118_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used_limit_choices_to', models.BooleanField(default=False, verbose_name='過去の試合を修正する')),
            ],
            options={
                'verbose_name': '設定',
                'verbose_name_plural': '設定',
            },
        ),
    ]
