# Generated by Django 2.2.6 on 2019-12-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0004_playersfielder_playerspitcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerspitcher',
            options={'verbose_name': '投手総合成績', 'verbose_name_plural': '投手総合成績'},
        ),
    ]
