# Generated by Django 2.2.6 on 2019-11-11 04:10

import django.core.validators
from django.db import migrations, models
import eikan.models.teams


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0004_auto_20191111_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='is_active_duty',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='teams',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '夏'), (2, '秋')], default=eikan.models.teams.default_period, verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='year',
            field=models.PositiveSmallIntegerField(default=eikan.models.teams.default_year, validators=[django.core.validators.MinValueValidator(1941)], verbose_name='年度'),
        ),
    ]
