# Generated by Django 2.2.6 on 2020-05-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('eikan', '0005_auto_20200522_1524'), ('eikan', '0006_auto_20200525_1327'), ('eikan', '0007_auto_20200525_1333'), ('eikan', '0008_auto_20200525_1337')]

    dependencies = [
        ('eikan', '0004_games_mamono_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldertotalresults',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='pitchertotalresults',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='teamtotalresults',
            name='team_id',
        ),
        migrations.AddField(
            model_name='fieldertotalresults',
            name='player',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AddField(
            model_name='pitchertotalresults',
            name='player',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='eikan.Players', verbose_name='選手'),
        ),
        migrations.AddField(
            model_name='teamtotalresults',
            name='team',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='eikan.Teams', verbose_name='チーム'),
        ),
        migrations.AddConstraint(
            model_name='teams',
            constraint=models.UniqueConstraint(fields=('year', 'period'), name='unique_team'),
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(fields=('admission_year', 'name'), name='unique_player'),
        ),
        migrations.AddConstraint(
            model_name='fielderresults',
            constraint=models.UniqueConstraint(fields=('game_id', 'player_id'), name='unique_fielderresult'),
        ),
        migrations.AddConstraint(
            model_name='pitcherresults',
            constraint=models.UniqueConstraint(fields=('game_id', 'player_id'), name='unique_pitcherresult'),
        ),
    ]
