# Generated by Django 2.2.13 on 2022-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0004_auto_20210116_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='is_scout',
            field=models.BooleanField(default=False, verbose_name='スカウト'),
        ),
    ]
