# Generated by Django 2.2.13 on 2022-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0005_players_is_scout'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='is_two_way',
            field=models.BooleanField(default=False, verbose_name='二刀流'),
        ),
    ]
