# Generated by Django 2.2.6 on 2020-05-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0005_auto_20200522_1524'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teams',
            constraint=models.UniqueConstraint(fields=('year', 'period'), name='unique_team'),
        ),
    ]
