# Generated by Django 2.2.6 on 2020-01-29 01:11

from django.db import migrations, models
import eikan.models.games


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0005_modelsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '弱小'), (2, 'そこそこ'), (3, '中堅'), (4, '強豪'), (5, '名門')], default=eikan.models.games.default_team_rank, verbose_name='ランク'),
        ),
    ]
