# Generated by Django 2.2.6 on 2020-05-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0006_auto_20200525_1327'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(fields=('admission_year', 'name'), name='unique_player'),
        ),
    ]
