# Generated by Django 2.2.6 on 2020-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0006_auto_20200129_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='rank',
        ),
        migrations.AddField(
            model_name='teamtotalresults',
            name='rank',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True, verbose_name='ランク'),
        ),
        migrations.AlterField(
            model_name='games',
            name='competiton_round',
            field=models.PositiveSmallIntegerField(choices=[('', '選択'), (1, '練習試合'), (2, '1回戦'), (3, '2回戦'), (4, '3回戦'), (6, '準々決勝'), (7, '準決勝'), (8, '決勝')], default=0, verbose_name='回戦'),
        ),
    ]
