# Generated by Django 2.2.27 on 2022-03-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0007_auto_20220318_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtotalresults',
            name='br',
            field=models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='BR'),
        ),
    ]
