# Generated by Django 2.2.6 on 2020-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0007_auto_20200130_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchertotalresults',
            name='h_9',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3, verbose_name='H/9'),
        ),
        migrations.AddField(
            model_name='pitchertotalresults',
            name='h_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='H%'),
        ),
    ]
