# Generated by Django 2.2.6 on 2020-05-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0007_auto_20200525_1333'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fielderresults',
            constraint=models.UniqueConstraint(fields=('game_id', 'player_id'), name='unique_fielderresult'),
        ),
        migrations.AddConstraint(
            model_name='pitcherresults',
            constraint=models.UniqueConstraint(fields=('game_id', 'player_id'), name='unique_pitcherresult'),
        ),
    ]
