# Generated by Django 2.2.6 on 2020-02-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0008_auto_20200216_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='bbhp_9',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='BBHP/9'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='era',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='防御率'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='h_9',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='H/9'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='h_percent',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='H%'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='hr_9',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='HR/9'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='hr_percent',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='HR%'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='k_9',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='K/9'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='k_bbhp',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='K/BBHP'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='k_percent',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='K%'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='lob_percent',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='LOB%'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='p_bbhp_percent',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='BBHP%'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='p_ip',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='P/IP'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='ura',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='失点率'),
        ),
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='whip',
            field=models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=6, verbose_name='WHIP'),
        ),
    ]
