# Generated by Django 2.2.6 on 2020-03-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0009_auto_20200218_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='competiton_round',
            new_name='competition_round',
        ),
    ]
