# Generated by Django 2.2.6 on 2020-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0010_auto_20200327_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchertotalresults',
            name='previous_game_pitched',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='前回登板'),
        ),
    ]
