# Generated by Django 2.2.6 on 2020-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eikan', '0011_pitchertotalresults_previous_game_pitched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchertotalresults',
            name='previous_game_pitched',
            field=models.FloatField(default=0.0, editable=False, verbose_name='前回登板'),
        ),
    ]
